### ISSUE TITLE
 The rule RandomRule is not exist

### ISSUE THREAD

**Issue by meodemsao** [nest-cloud/nestcloud#44]
I have this issue when using nestcloud@0.7.17 and nestjs@8.x

```(node:42295) UnhandledPromiseRejectionWarning: Error: The rule RandomRule is not exist
    at Timeout._onTimeout (/Users/username/Desktop/Projects/nest-cqrs-auth/node_modules/@nestcloud/loadbalance/loadbalance.js:90:45)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
(Use `node --trace-warnings ...` to show where the warning was created```

**Comment by anduong96** [comment]
Related #45 

Published this for a temporary fix: 
https://github.com/anduong96/nestcloud2
